server:
  port: 8081

spring:
  application:
    name: prince-weather-mcp-server
  data:
    redis:
      host: localhost
      port: 6379
      username: redis
      password: redis
      database: 0
  ai:
    mcp:
      server:
        name: prince-weather-mcp-server
        version: 1.0.0
        type: sync
#        sse-message-endpoint: /sse/mcp/weather
        protocol: streamable
        annotation-scanner:
          enabled: true